
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package client.sayhi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T15:57:08.872+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldImplService",
                      portName = "HelloWorldImplPort",
                      targetNamespace = "http://internal.cxfservice.lessonslab.com/",
                      wsdlLocation = "http://localhost:8080/CxfService/soap/helloservices?wsdl",
                      endpointInterface = "client.sayhi.IHelloWorld")
                      
public class HelloWorldImplPortImpl implements IHelloWorld {

    private static final Logger LOG = Logger.getLogger(HelloWorldImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see client.sayhi.IHelloWorld#sayHi(java.lang.String  text )*
     */
    public java.lang.String sayHi(java.lang.String text) { 
        LOG.info("Executing operation sayHi");
        System.out.println(text);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
