package client.sayhi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T15:57:08.882+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", name = "IHelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", className = "client.sayhi.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", className = "client.sayhi.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
