
package client.sayhi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T15:57:08.886+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class IHelloWorld_HelloWorldImplPort_Server{

    protected IHelloWorld_HelloWorldImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldImplPortImpl();
        String address = "http://localhost:8080/CxfService/soap/helloservices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IHelloWorld_HelloWorldImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
