
package client.employee;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T16:56:47.563+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class EmployeeSoapService_EmployeeServiceSoapImplPort_Server{

    protected EmployeeSoapService_EmployeeServiceSoapImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EmployeeServiceSoapImplPortImpl();
        String address = "http://localhost:8080/CxfService/soap/employeeservices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new EmployeeSoapService_EmployeeServiceSoapImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
