package client.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T16:56:47.567+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "EmployeeServiceSoapImplService", 
                  wsdlLocation = "http://localhost:8080/CxfService/soap/employeeservices?wsdl",
                  targetNamespace = "http://internal.cxfservice.lessonslab.com/") 
public class EmployeeServiceSoapImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://internal.cxfservice.lessonslab.com/", "EmployeeServiceSoapImplService");
    public final static QName EmployeeServiceSoapImplPort = new QName("http://internal.cxfservice.lessonslab.com/", "EmployeeServiceSoapImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CxfService/soap/employeeservices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeServiceSoapImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CxfService/soap/employeeservices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeServiceSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeServiceSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceSoapImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EmployeeServiceSoapImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeServiceSoapImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeServiceSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EmployeeSoapService
     */
    @WebEndpoint(name = "EmployeeServiceSoapImplPort")
    public EmployeeSoapService getEmployeeServiceSoapImplPort() {
        return super.getPort(EmployeeServiceSoapImplPort, EmployeeSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeSoapService
     */
    @WebEndpoint(name = "EmployeeServiceSoapImplPort")
    public EmployeeSoapService getEmployeeServiceSoapImplPort(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceSoapImplPort, EmployeeSoapService.class, features);
    }

}
