package client.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-31T16:56:47.558+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", name = "EmployeeSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeSoapService {

    @WebMethod
    @RequestWrapper(localName = "getEmployeeDetail", targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", className = "client.employee.GetEmployeeDetail")
    @ResponseWrapper(localName = "getEmployeeDetailResponse", targetNamespace = "http://soapinterface.cxfservice.lessonslab.com/", className = "client.employee.GetEmployeeDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public client.employee.Employee getEmployeeDetail(
        @WebParam(name = "employeeId", targetNamespace = "")
        java.lang.String employeeId
    );
}
